apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-processor-api
  labels:
    app: tweet-processor
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-processor
  template:
    metadata:
      labels:
        app: tweet-processor
        version: v2
    spec:
      containers:
        - name: tweet-processor
          image: docker.io/johnlenon003/api-processor:v2
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_PASSWORD
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_DB_NAME
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_CONNECTION_STRING
            - name: MONGODB_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGODB_COLLECTION
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always
