apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tweet-processor

resources:
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

labels:
  - pairs:
      app: tweet-processor
      project: hostile-tweets-ex

namespace: lkey09211-dev
