apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  labels:
    app: tweet-processor
type: Opaque
data:
  # Base64 encoded values
  # IRGC -> SVJHQW==
  # iraniraniran -> aXJhbmlyYW5pcmFu
  # IranMalDB -> SXJhbk1hbERCCg==
  # mongodb+srv://IRGC:iraniraniran@iranmaldb.gurutam.mongodb.net/ -> bW9uZ29kYitzcnY6Ly9JUkdDOmlyYW5pcmFuaXJhbkBpcmFubWFsZGIuZ3VydXRhbS5tb25nb2RiLm5ldC8=
  # tweets -> dHdlZXRz
  USER: SVJHQW==
  MONGO_PASSWORD: aXJhbmlyYW5pcmFu
  MONGO_DB_NAME: SXJhbk1hbERCCg==
  MONGO_CONNECTION_STRING: bW9uZ29kYitzcnY6Ly9JUkdDOmlyYW5pcmFuaXJhbkBpcmFubWFsZGIuZ3VydXRhbS5tb25nb2RiLm5ldC8=
  MONGODB_COLLECTION: dHdlZXRz
